services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"  # Libera o acesso à API
    volumes:
      - ./data:/app/data
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=trello_db
    ports:
      - "5432:5432"
