version: '3.8'

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"  # Permite que você acesse http://localhost:8000
    # Removi o volumes e o depends_on porque o banco agora é externo (Supabase)
    restart: always
