services:
  app:
    build: .
    
    environment:
      - TRELLO_API_KEY=${TRELLO_API_KEY}
      - TRELLO_TOKEN=${TRELLO_TOKEN}
      - TRELLO_BOARD_ID=${TRELLO_BOARD_ID}
      - DIRECT_URL=${DIRECT_URL}
    ports:
      - "8000:8000"
