name: Trello Pipeline

on:
  schedule:
    # 08:00 Brasília = 11:00 UTC
    - cron: '0 11 * * *'
  workflow_dispatch: 

jobs:
  run-etl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar Pipeline
        env:
          # O GitHub injeta as Secrets aqui como variáveis de ambiente reais
          TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
          TRELLO_TOKEN: ${{ secrets.TRELLO_TOKEN }}
          TRELLO_BOARD_ID: ${{ secrets.TRELLO_BOARD_ID }}
          DIRECT_URL: ${{ secrets.DIRECT_URL }}
        run: |
          # Adiciona a pasta 'app' ao caminho de busca do Python para evitar erros de importação
          export PYTHONPATH=$PYTHONPATH:$(pwd)/app
          python app/main.py